const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923165167688" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "md",
  ownername:process.env.OWNER_NAME|| "It'x crazy",

  sessionName:process.env.SESSION_ID || "SUHAIL_07_13_09_24_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQwLFxuICAgICAgICA4LFxuICAgICAgICAyMzUsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTk3LFxuICAgICAgICAxMTcsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTE1LFxuICAgICAgICA4MixcbiAgICAgICAgNTQsXG4gICAgICAgIDEzNCxcbiAgICAgICAgNTQsXG4gICAgICAgIDk5LFxuICAgICAgICA1OSxcbiAgICAgICAgNDcsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTUzLFxuICAgICAgICAxMzcsXG4gICAgICAgIDMwLFxuICAgICAgICAxNTUsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTc4LFxuICAgICAgICAxNTksXG4gICAgICAgIDY2LFxuICAgICAgICAxNTAsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTcyLFxuICAgICAgICA4MCxcbiAgICAgICAgNTYsXG4gICAgICAgIDEyNixcbiAgICAgICAgODksXG4gICAgICAgIDc3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDc0LFxuICAgICAgICAxNjIsXG4gICAgICAgIDE3MCxcbiAgICAgICAgNDcsXG4gICAgICAgIDcsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMjAsXG4gICAgICAgIDc2LFxuICAgICAgICAyNDEsXG4gICAgICAgIDc5LFxuICAgICAgICA4MyxcbiAgICAgICAgMjQyLFxuICAgICAgICAxNjksXG4gICAgICAgIDExMixcbiAgICAgICAgODYsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMjQsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMDUsXG4gICAgICAgIDYxLFxuICAgICAgICAxNDcsXG4gICAgICAgIDcwLFxuICAgICAgICAzNyxcbiAgICAgICAgMTg1LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMjE3LFxuICAgICAgICAxMzgsXG4gICAgICAgIDM3LFxuICAgICAgICAyMTMsXG4gICAgICAgIDYyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDAsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNTYsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTEyLFxuICAgICAgICAyNDQsXG4gICAgICAgIDM1LFxuICAgICAgICAxMDMsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTUwLFxuICAgICAgICAyMjQsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTkxLFxuICAgICAgICAxMjgsXG4gICAgICAgIDEwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDE5LFxuICAgICAgICA0MCxcbiAgICAgICAgMTUzLFxuICAgICAgICAxMTAsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTgsXG4gICAgICAgIDc1LFxuICAgICAgICAxMDQsXG4gICAgICAgIDIxMSxcbiAgICAgICAgODgsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMDMsXG4gICAgICAgIDgxLFxuICAgICAgICAxMjYsXG4gICAgICAgIDEwMVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjUsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjI0LFxuICAgICAgICAxLFxuICAgICAgICAxNTMsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTEzLFxuICAgICAgICAzNSxcbiAgICAgICAgMTgxLFxuICAgICAgICAyMDUsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTAwLFxuICAgICAgICA4OCxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMTcsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMSxcbiAgICAgICAgMjM2LFxuICAgICAgICAxNTEsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjE0LFxuICAgICAgICAxMTYsXG4gICAgICAgIDgyLFxuICAgICAgICAzOSxcbiAgICAgICAgMTksXG4gICAgICAgIDQ0LFxuICAgICAgICAyMTYsXG4gICAgICAgIDEsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTczLFxuICAgICAgICAyMzUsXG4gICAgICAgIDM5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4MCxcbiAgICAgICAgNjIsXG4gICAgICAgIDg5LFxuICAgICAgICAxOTcsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTYyLFxuICAgICAgICAyNDksXG4gICAgICAgIDQ2LFxuICAgICAgICA1NyxcbiAgICAgICAgMjEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTM5LFxuICAgICAgICA0NyxcbiAgICAgICAgNDgsXG4gICAgICAgIDE4LFxuICAgICAgICAyMjgsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTgyLFxuICAgICAgICAxNzYsXG4gICAgICAgIDY1LFxuICAgICAgICAzMCxcbiAgICAgICAgMTc0LFxuICAgICAgICAxNDUsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTEzLFxuICAgICAgICAxMDIsXG4gICAgICAgIDIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMTcsXG4gICAgICAgIDEzOSxcbiAgICAgICAgNzBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTgzLFxuICAgICAgICAyOCxcbiAgICAgICAgMjIwLFxuICAgICAgICAyMjUsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTI2LFxuICAgICAgICAzMSxcbiAgICAgICAgNjYsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjAwLFxuICAgICAgICA1MCxcbiAgICAgICAgMjAsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjE1LFxuICAgICAgICAxMDgsXG4gICAgICAgIDczLFxuICAgICAgICAxOCxcbiAgICAgICAgMzgsXG4gICAgICAgIDExLFxuICAgICAgICAxNzcsXG4gICAgICAgIDEyMSxcbiAgICAgICAgNjAsXG4gICAgICAgIDk0LFxuICAgICAgICAxMzEsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMjcsXG4gICAgICAgIDI3LFxuICAgICAgICAyMTEsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxOTQsXG4gICAgICAgIDEyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIwMCxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMTkzLFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICA3MlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAzNixcbiAgICAgICAgICAzNixcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAyOCxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAyNixcbiAgICAgICAgICAyMSxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgOSxcbiAgICAgICAgICA0NCxcbiAgICAgICAgICA5M1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTYxLFxuICAgICAgICAyNDcsXG4gICAgICAgIDE4MixcbiAgICAgICAgOTYsXG4gICAgICAgIDExOSxcbiAgICAgICAgODIsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTQzLFxuICAgICAgICAxMDksXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjIxLFxuICAgICAgICAyNDAsXG4gICAgICAgIDE0OCxcbiAgICAgICAgNSxcbiAgICAgICAgMTA0LFxuICAgICAgICAxOSxcbiAgICAgICAgMjQwLFxuICAgICAgICA2MyxcbiAgICAgICAgOTQsXG4gICAgICAgIDEyLFxuICAgICAgICA4NSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxMTEsXG4gICAgICAgIDgxLFxuICAgICAgICAxLFxuICAgICAgICAxMixcbiAgICAgICAgMTcwLFxuICAgICAgICAyMSxcbiAgICAgICAgMTAzLFxuICAgICAgICAxMTEsXG4gICAgICAgIDI1NSxcbiAgICAgICAgNzgsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjIyLFxuICAgICAgICAxNTksXG4gICAgICAgIDE3MSxcbiAgICAgICAgODksXG4gICAgICAgIDcwLFxuICAgICAgICAyMjUsXG4gICAgICAgIDY1LFxuICAgICAgICA2MyxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNDMsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNzMsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNjUsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTExLFxuICAgICAgICA5MSxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMDUsXG4gICAgICAgIDI4LFxuICAgICAgICAyLFxuICAgICAgICA2MSxcbiAgICAgICAgMjUwLFxuICAgICAgICAxNyxcbiAgICAgICAgMTA4LFxuICAgICAgICAyMDEsXG4gICAgICAgIDI1LFxuICAgICAgICA5NSxcbiAgICAgICAgOTMsXG4gICAgICAgIDJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDU4LFxuICBcImFkdlNlY3JldEtleVwiOiBcIkNNb2pyUUFIZ3dPZlRVNlN0aXB1RWZwWTBaY01pZm5pUTFudGlic2V1Ymc9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMTY1MTY3Njg4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIyODFGQkRDRDk2NjMxODRGQjM0NzkxQTE5RTgyNDkxNlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjcxNjE5NzRcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMxNjUxNjc2ODhAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkIxMDBCNEU0QTA0M0M5QUI4NjZFQkM0NkRCMzQ5ODQyXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNzE2MTk3NFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJmTFFoZ1ZscFFaS2paa3I2VjRLVUJ3XCIsXG4gIFwicGhvbmVJZFwiOiBcIjk3YTBjNTJjLTkxMTAtNGU0Ni1iYzU4LWE1MDQ3ZmM4ZjllYlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMzcsXG4gICAgICAxMjksXG4gICAgICAyNDEsXG4gICAgICA3LFxuICAgICAgMTIzLFxuICAgICAgMTk2LFxuICAgICAgMTI1LFxuICAgICAgMzksXG4gICAgICA2LFxuICAgICAgNDUsXG4gICAgICAyMTIsXG4gICAgICAxNDAsXG4gICAgICAyNDAsXG4gICAgICAyMjgsXG4gICAgICAxNTYsXG4gICAgICAzLFxuICAgICAgMTUzLFxuICAgICAgMTk4LFxuICAgICAgMjUsXG4gICAgICA5MlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAwLFxuICAgICAgODEsXG4gICAgICA3NCxcbiAgICAgIDE1MixcbiAgICAgIDg1LFxuICAgICAgMjAxLFxuICAgICAgMjMyLFxuICAgICAgMTAsXG4gICAgICA3NixcbiAgICAgIDE5MCxcbiAgICAgIDE2OSxcbiAgICAgIDIzNSxcbiAgICAgIDE2OSxcbiAgICAgIDE3OCxcbiAgICAgIDE1LFxuICAgICAgMTIwLFxuICAgICAgMTY0LFxuICAgICAgNTUsXG4gICAgICAxMTAsXG4gICAgICA5MFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJKQk03N0dQVFwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTIzMTY1MTY3Njg4OjVAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjE1OTE3NjI4NjI3NzczNzo1QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIuGsiuGsgVTMt+GOu+GOrCjil6PigLjil6Ip4oSt4oSbw4XihKTCpeC/lOC+gOGthMK5wrMg8J+mtFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ04rZ2huWVE4TXpKdHdZWUFTQUFLQUE9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwic0JLREMrYTZOdFNPV05aaE5DcEsySkNSQjgvTWZnUTQyN2p5UkhKaFhWbz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJySDF4UXpuRUhoSnJBaDRmVzlrWHVXRzhwSkhhbS9yYWlUbUE5Z1ZkL0tCYkI2d1VJMWNPNS9ZeUxhQ0FEU0l2SWpaWStkV2ZuMUJ2anZJNDJaTUdCUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJCR3Z1alpRdG4vc1RoWEFkaVFUbm9IcFk0YTZtY09CaEpudDFaenk4WmorMS9IQk1iUllWMDZObHRQU2xLMHBNcnJzbklDaHJNYkhNRTNUaHprWStEQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMxNjUxNjc2ODg6NUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICA1NCxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA5NyxcbiAgICAgICAgICA1MixcbiAgICAgICAgICA0MixcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDQsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDkwXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjcxNjE5NzIsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFHcjVcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUdyNS5qc29uIjogIntcImtleURhdGFcIjpcImJ0TXZNMDJqNTB6VTYwSXowM0Y2aW51MVlVSHlnOVF5SjQ0VTRRRHppUFU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjQ3NTY2NDMxLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjcxNjE5NzUwNDJcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
